bag/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        "",
        views.view_bag,
        name="view_bag"
        ),
    path(
        "add/<int:item_id>/",
        views.add_to_bag,
        name="add_to_bag"
        ),
    path(
        "update/<int:item_id>/",
        views.update_bag,
        name="update_bag"
        ),
    path(
        "remove/<int:item_id>/",
        views.remove_from_bag,
        name="remove_from_bag"
        ),
]

profiles/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path("",
         views.RedirectProfileView.as_view(),
         name="profile_redirect"
         ),
    path(
        "user/",
        views.UpdateUsernameView.as_view(),
        name="profile_user"
        ),
    path(
        "profile/",
        views.ProfileView.as_view(),
        name="profile"
        ),
    path(
        "orders/",
        views.OrderListView.as_view(),
        name="profile_orders"
        ),
    path(
        "orders/<str:order_number>/",
        views.OrderDetailView.as_view(),
        name="order_view"
    ),
    path(
        "delete/",
        views.delete_profile,
        name="delete_profile"
        ),
    path(
        "login/",
        CustomLoginView.as_view(),
        name="profile_login"
        ),
    path(
        "logout/",
        CustomLogoutView.as_view(),
        name="profile_logout"
        ),
]

road_ready_driving/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(
        "admin/",
        admin.site.urls
        ),
    path(
        "accounts/",
        include("allauth.urls")
        ),  # Allauth URLs
    path(
        "",
        include("home.urls")
        ),  # Home URLs
    path(
        "packages/",
        include("packages.urls")
        ),  # Packages URLs
    path(
        "bag/",
        include("bag.urls")
        ),  # Bag URLs
    path(
        "checkout/",
        include("checkout.urls")
        ),  # Checkout URLs
    path(
        "profiles/",
        include("profiles.urls")
        ),  # Profiles URLs
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = "road_ready_driving.views.handler404"

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    default_full_name = models.CharField(
        max_length=50,
        null=True,
        blank=True
        )
    default_email = models.EmailField(
        max_length=254,
        null=True,
        blank=True)
    default_phone_number = models.CharField(
        max_length=20,
        null=True,
        blank=True
        )
    default_country = CountryField(
        blank_label="-- Select Country --", null=True, blank=True
    )
    default_street_address1 = models.CharField(
        max_length=80,
        null=True,
        blank=True
        )
    default_street_address2 = models.CharField(
        max_length=80,
        null=True,
        blank=True
        )
    default_town_or_city = models.CharField(
        max_length=40,
        null=True,
        blank=True
        )
    default_county = models.CharField(
        max_length=80,
        null=True,
        blank=True
        )
    default_postcode = models.CharField(
        max_length=20,
        null=True,
        blank=True
        )

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    else:
        try:
            instance.userprofile.save()
        except UserProfile.DoesNotExist:
            UserProfile.objects.create(user=instance)

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class UpdateUsernameForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({"class": "form-control"})

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if User.objects.filter(
                username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError(
                "This username is already taken. Please choose another one."
            )
        return username


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ("user",)
        fields = (
            "default_full_name",
            "default_email",
            "default_phone_number",
            "default_country",
            "default_street_address1",
            "default_street_address2",
            "default_town_or_city",
            "default_county",
            "default_postcode",
        )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if self.fields.get("default_email") and user:
            self.fields["default_email"].initial = user.email
            self.fields["default_email"].widget.attrs["readonly"] = True

        placeholders = {
            "default_full_name": "Full Name",
            "default_email": "Email Address",
            "default_phone_number": "Phone Number",
            "default_postcode": "Postal Code",
            "default_town_or_city": "Town or City",
            "default_street_address1": "Street Address 1",
            "default_street_address2": "Street Address 2",
            "default_county": "County/State",
            "default_country": "Country",
        }
        self.fields["default_full_name"].widget.attrs["autofocus"] = True
        for field in self.fields:
            if field != "default_country":
                if field == "default_email" and user:
                    placeholder = user.email
                else:
                    placeholder = (
                        f"{placeholders[field]} *"
                        if self.fields[field].required
                        else placeholders[field]
                    )
                self.fields[field].widget.attrs["placeholder"] = placeholder
            self.fields[field].widget.attrs["class"] = "stripe-style-input"
            self.fields[field].label = False

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView
from django.views.generic.base import RedirectView
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import UpdateUsernameForm, UserProfileForm
from checkout.models import Order
from .models import UserProfile
from allauth.account.forms import LoginForm
from django.contrib.auth import logout
from django.http import JsonResponse
from allauth.account.views import LoginView as AllauthLoginView
from allauth.account.views import LogoutView as AllauthLogoutView


class CustomLoginView(AllauthLoginView):
    template_name = "allauth/login.html"
    form_class = LoginForm

    def form_valid(self, form):
        self.user = form.user
        login(self.request, self.user)

        messages.success(
            self.request, f"{self.user.username} has logged in successfully."
        )
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy("profile")


class CustomLogoutView(AllauthLogoutView):
    template_name = "allauth/logout.html"

    def post(self, request, *args, **kwargs):
        # Log the user out
        logout(request)
        # Add custom success message
        messages.success(request, "User successfully logged out.")
        return redirect(self.get_success_url())

    def get_success_url(self):
        # Redirect to login page after logout
        return reverse_lazy("account_login")


@method_decorator(login_required, name="dispatch")
class UpdateUsernameView(FormView):
    template_name = "profiles/update_username.html"
    form_class = UpdateUsernameForm
    success_url = reverse_lazy("profile_user")

    def get_form(self, form_class=None):
        return self.form_class(
            self.request.POST if self.request.method == "POST" else None,
            instance=self.request.user,
        )

    def form_valid(self, form):
        form.save()
        if self.request.headers.get("X-Requested-With") == "XMLHttpRequest":
            messages.success(
                self.request, "Your username has been updated successfully!"
            )
            return JsonResponse({"success": True})
        messages.success(self.request,
                         "Your username has been updated successfully!")
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get("X-Requested-With") == "XMLHttpRequest":
            return JsonResponse(
                {
                    "success": False,
                    "error": form.errors.get("username", ["Unknown error"])[0],
                },
                status=400,
            )
        messages.error(
            self.request,
            "There was an error updating your username. Please try again."
        )
        return super().form_invalid(form)


@method_decorator(login_required, name="dispatch")
class RedirectProfileView(RedirectView):
    pattern_name = "profile_user"

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_staff or self.request.user.is_superuser:
            self.pattern_name = "profile_user"
        else:
            self.pattern_name = "profile"
        return super().get_redirect_url(*args, **kwargs)


@method_decorator(login_required, name="dispatch")
class ProfileView(FormView):
    template_name = "profiles/profile.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("profile")

    def get_form(self, form_class=None):
        return self.form_class(
            instance=self.request.user.userprofile,
            data=self.request.POST if self.request.method == "POST" else None,
            user=self.request.user,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile_form"] = self.get_form()
        return context

    def form_valid(self, form):
        profile = form.save(commit=False)
        user = self.request.user

        if profile.default_email and profile.default_email != user.email:
            user.email = profile.default_email
            user.save()

        elif user.email != profile.default_email != user.email:
            profile.default_email = user.email

        profile.save()
        messages.success(self.request, "Your profile has been updated.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,
                       "Please correct the errors and try again.")
        return super().form_invalid(form)


@method_decorator(login_required, name="dispatch")
class OrderListView(FormView):
    template_name = "profiles/orders.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("profile_orders")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            user_profile = self.request.user.userprofile
            context["orders"] = Order.objects.filter(
                user_profile=user_profile
            ).order_by("-date")
        except UserProfile.DoesNotExist:
            context["orders"] = Order.objects.none()
        return context


@method_decorator(login_required, name="dispatch")
class OrderDetailView(FormView):
    template_name = "profiles/order_detail.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("profile_orders")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = get_object_or_404(
            Order,
            order_number=self.kwargs["order_number"],
            user_profile=self.request.user.userprofile,
        )
        context["order"] = order
        return context


@login_required
def delete_profile(request):
    if request.method == "POST":
        user = request.user
        user.delete()
        messages.success(request,
                         "Your profile has been successfully deleted.")
        return redirect("account_login")
    return render(request, "profiles/delete_profile.html")

profiles/templates/profiles/account.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/account_management.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
{% endblock %}

{% block content %}
    {% include 'profiles/includes/menu.html' %}
    <div role="main" class="page-container mt-3">
        {% block account_content %}{% endblock %}
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script src="{% static 'js/profile.js' %}" defer></script>
{% endblock %}

profiles/templates/profiles/delete_profile.html
{% extends 'profiles/account.html' %}
{% load i18n %}

{% block account_content %}
  <div class="overlay"></div>
  <div role="main" aria-labelledby="delete-profile" class="page-container">
    <h1 class="mb-5" id="delete-profile">{% trans 'Delete Profile' %}</h1>
    <hr />

    {% if messages %}
      <div class="messages mb-4">
        {% for message in messages %}
          <div class="alert {% if message.tags == 'success' %}
              
                alert-success
            {% elif message.tags == 'error' %}
              
                alert-danger
            {% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="btn-close"
            data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      </div>
    {% endif %}

    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <p>
        Are you sure you want to delete your profile?
        This action cannot be undone.
        </p>
        <form method="POST" action="{% url 'delete_profile' %}">
          {% csrf_token %}
          <div class="button-group">
            <button type="submit" class="btn btn-danger">
                {% trans 'Delete Profile' %}</button>
            <a href="{% url 'profile' %}" class="btn btn-secondary">
                {% trans 'Cancel' %}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

profiles/templates/profiles/order_detail.html
{% extends "profiles/account.html" %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/account_management.css' %}">

{% block account_content %}
<div class="overlay"></div>
<div role="main" aria-labelledby="order-detail" class="page-container">
    <div class="order-header-wrapper">
        <h4 class="mb-5" id="order-detail">
            Order: 
            <span class="order-number d-inline-block d-md-inline">
                {{ order.order_number }}
            </span>
        </h4>
    </div>
    
    <hr>
    <div class="row">
        <div class="col-12 col-lg-6">
            <h5 class="text-muted">Your Details</h5>
            <p><strong>Name:</strong>
                {{ order.full_name }}
            </p>
            <p><strong>Email:</strong>
                {{ order.email }}
            </p>
            <p><strong>Phone:</strong>
                {{ order.phone_number }}
            </p>
            <p><strong>Address:</strong>
                {{ order.street_address1 }},
                {{ order.street_address2 }},
                {{ order.town_or_city }},
                {{ order.country }},
                {{ order.postcode }}
            </p>
        </div>
        <div class="col-12 col-lg-6">
            <h5 class="text-muted">Order Summary</h5>
            {% for item in order.lineitems.all %}
                <div class="row">
                    <!-- Stack columns on mobile -->
                    <div class="col-12 col-md-8">
                        <p>
                            {{ item.package.name }} (Qty: {{ item.quantity }})
                        </p>
                    </div>
                    <div class="col-12 col-md-4 text-md-right">
                        <p>£{{ item.lineitem_total|floatformat:2 }}</p>
                    </div>
                </div>
            {% endfor %}
            <hr>
            <!-- Stack grand total on mobile -->
            <div class="row">
                <div class="col-12 col-md-8">
                    <p><strong>Grand Total:</strong></p>
                </div>
                <div class="col-12 col-md-4 text-md-right">
                    <p>
                        <strong>£{{ order.grand_total|floatformat:2 }}</strong>
                    </p>
                </div>
            </div>
        </div>
        <!-- Button on mobile -->
        <div class="text-center mt-4 col-12">
            <a href="{% url 'profile_orders' %}"
            class="btn btn-primary d-block d-md-inline-block">
                <i class="fas fa-arrow-left"></i> Return to Orders
            </a>
        </div>
    </div>
</div>
{% endblock %}

profiles/templates/profiles/orders.html
{% extends 'profiles/account.html' %}

{% block account_content %}
  <div class="overlay"></div>
  <div role="main" aria-labelledby="orders" class="page-container">
    <h1 class="mb-5" id="orders">My Orders</h1>
    <hr />
    <div class="row">
      <div class="col-12">
        {% if orders %}
          <table class="table">
            <thead>
              <tr>
                <th>Order Details</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
                <tr>
                  <td>
                    <div class="order-card">
                      <span class="order-number">
                        <strong>Order Number:</strong> {{ order.order_number }}
                    </span>
                      <span>
                        <strong>Date:</strong> {{ order.date }}
                    </span>
                      <span>
                        <strong>Total:</strong>
                        £{{ order.grand_total|floatformat:2 }}</span>
                      <span class="order-buttons">
                        <a href="
                        {% url 'home' %}"
                        class="btn btn-sm btn-primary">Go Home
                    </a>
                        <a href="
                        {% url 'order_view' order.order_number %}" 
                        class="btn btn-sm btn-primary">View Order</a>
                      </span>
                    </div>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>You have no orders yet.</p>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="btt-button shadow-sm rounded-0 border border-black">
    <a href="#" class="btt-link d-flex h-100">
        <i class="fas fa-arrow-up text-black mx-auto my-auto"></i></a>
  </div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'profiles/account.html' %}
{% load static %}


{% block account_content %}
  <div class="overlay"></div>
  <div role="main" aria-labelledby="profile" class="profile page-container">
    <h1 class="mb-5" id="profile">My Profile</h1>
    <hr />

    {% if messages %}
      <div class="messages mb-4">
        {% for message in messages %}
          <div class="alert {% if message.tags == 'success' %}
              alert-success
            {% elif message.tags == 'error' %}
              alert-danger
            {% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="btn-close"
            data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      </div>
    {% endif %}

    <div class="row">
      <div class="col-12">
        <form action="{% url 'profile' %}" method="POST" id="payment-form">
          {% csrf_token %}
          <fieldset class="rounded px-3 mb-5">
            <legend class="fieldset-label small px-2 w-auto">Personal</legend>
            <br />
            <label for="id_default_full_name"></label>
            {{ profile_form.default_full_name|as_crispy_field }}
            <label for="id_default_email"></label>
            {{ profile_form.default_email|as_crispy_field }}
            <label for="id_default_phone_number"></label>
            {{ profile_form.default_phone_number|as_crispy_field }}
          </fieldset>
          <fieldset class="rounded px-3 mb-5">
            <legend class="fieldset-label small px-2 w-auto"></legend>
            <br />
            <label for="id_default_street_address1"></label>
            {{ profile_form.default_street_address1|as_crispy_field }}
            <label for="id_default_street_address2"></label>
            {{ profile_form.default_street_address2|as_crispy_field }}
            <label for="id_default_town_or_city"></label>
            {{ profile_form.default_town_or_city|as_crispy_field }}
            <label for="id_default_county"></label>
            {{ profile_form.default_county|as_crispy_field }}
            <label for="id_default_postcode"></label>
            {{ profile_form.default_postcode|as_crispy_field }}
            <label for="id_default_country"></label>
            {{ profile_form.default_country|as_crispy_field }}
          </fieldset>
          <div class="submit-button mt-5 mb-2 px-3 text-end">
            <button type="submit" class="btn btn-secondary"><span
            class="font-weight-bold">Save</span></button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

profiles/templates/profiles/update_username.html
{% extends "profiles/account.html" %}
{% load static %}

{% block account_content %}
<div class="overlay"></div>
<div role="main" aria-labelledby="username" class="page-container">
    <div class="text-center mb-4">
        <h1 class="mb-0" id="username">Update Username</h1>
        <hr class="w-25 mx-auto">

        {% if messages %}
      <div class="messages mb-4">
        {% for message in messages %}
          <div class="alert {% if message.tags == 'success' %}
              alert-success
            {% elif message.tags == 'error' %}
              alert-danger
            {% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="btn-close"
            data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      </div>
    {% endif %}
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <form method="POST" id="username-form"
            action="{% url 'profile_user' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-start">
                    <button type="submit"
                    class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}